CREATE TABLE card_hit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bin       VARCHAR(255),
    hit_count INT                                     NOT NULL,
    CONSTRAINT pk_cardhit PRIMARY KEY (id)
);

CREATE TABLE customer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

ALTER TABLE card_hit
    ADD CONSTRAINT uc_cardhit_bin UNIQUE (bin);